hypershift:
  region: us-east-1
  externalDns:
    domain: ''
    image: registry.redhat.io/edo/external-dns-rhel9:c8f7fbd233b9fbcc312672a6e5afd020655c791f
  hypershift:
    image: quay.io/rrp-dev-ci/hypershift-operator:ci-85824-2103217223685378048
    controlPlaneOperatorImage: quay.io/rrp-dev-ci/control-plane-operator:ci-85824-2103217223685378048
