apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-ratelimit-config
  namespace: {{ .Release.Namespace }}
data:
  redis.conf: |
    port {{ .Values.redis.port }}
    bind 0.0.0.0
    protected-mode no
    maxmemory {{ .Values.redis.config.maxmemory }}
    maxmemory-policy {{ index .Values.redis.config "maxmemory-policy" }}
    save {{ .Values.redis.config.save | quote }}
    appendonly {{ .Values.redis.config.appendonly }}
    tcp-keepalive 60
    timeout 300
