deployment_name: "{{ aws_region }}{% if eph_prefix %}-{{ eph_prefix }}{% endif %}"

dns:
  domain: "{% if ci %}ci00{% else %}dev0{% endif %}.rosa.devshift.net"

regional_cluster:
  enable_bastion: true
  enable_rate_limit_redis: true
  node_instance_families: ["m8i-flex", "m7i-flex"]

management_cluster_defaults:
  enable_bastion: true
  node_instance_families: ["m8i-flex", "m7i-flex"]

observability:
  pagerduty:
    enabled: false

platformApi:
  app:
    image:
      repository: quay.io/travi/rosa-hyperfleet-api
      tag: "ratelimit"
