deployment_name: '{{ aws_region }}{% if eph_prefix %}-{{ eph_prefix }}{% endif %}'
dns:
  domain: '{% if ci %}ci00{% else %}dev0{% endif %}.rosa.devshift.net'
regional_cluster:
  enable_bastion: true
  enable_write_sre_tools: true
  node_instance_families:
  - m8i-flex
  - m7i-flex
  hyperfleet_db_instance_class: db.t4g.medium
  hyperfleet_db_deletion_protection: false
  hyperfleet_db_skip_final_snapshot: true
  hyperfleet_db_performance_insights_enabled: false
  hyperfleet_db_monitoring_interval: 0
  enable_sre_tools_gateway: true
  enable_sre_public_access: false
  oidcS3Bucket: hypershift-{{ eph_prefix }}-regional-oidc-{{ account_id }}
management_cluster_defaults:
  enable_bastion: true
  node_instance_families:
  - m8i-flex
  - m7i-flex
observability:
  pagerduty:
    enabled: false
