provision_mcs:
  mc01:
    delete: true
applications:
  regional-cluster:
    platformApi:
      app:
        image:
          repository: quay.io/cdoan0/rosa-hyperfleet-api
          tag: ROSAENG-64871
    hyperfleet:
      helmValues:
        image:
          repository: quay.io/cdoan0/rosa-hyperfleet-operator
          tag: ROSAENG-64871
aws:
  account_id: '599476212575'
  management_cluster_account_id: '855246887846'
delete: true
