{{- $clusterName := required "global.cluster_name must be set via ApplicationSet valuesObject" .Values.global.cluster_name -}}
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: fips
spec:
  amiSelectorTerms:
    - alias: bottlerocket@latest
  instanceProfile: {{ $clusterName }}-karpenter-node-role
  subnetSelectorTerms:
    - tags:
        kubernetes.io/cluster/{{ $clusterName }}: owned
  securityGroupSelectorTerms:
    - tags:
        aws:eks:cluster-name: {{ $clusterName }}
  metadataOptions:
    httpTokens: required
    httpPutResponseHopLimit: 2
