apiVersion: v2
name: kata-deploy
description: Kata Containers runtime installation via upstream Helm chart
type: application
version: 0.2.0
dependencies:
  - name: kata-deploy
    version: "3.27.0"
    repository: "oci://ghcr.io/kata-containers/kata-deploy-charts"
