apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kata-deploy
spec:
  selector:
    matchLabels:
      app: kata-deploy
  template:
    metadata:
      labels:
        app: kata-deploy
    spec:
      nodeSelector:
        {{- toYaml .Values.kataDeploy.nodeSelector | nindent 8 }}
      tolerations:
        - key: hypershift.openshift.io/request-serving-component
          operator: Exists
          effect: NoSchedule
      serviceAccountName: kata-deploy
      containers:
        - name: kata-deploy
          image: {{ .Values.kataDeploy.image }}
          command:
            - /opt/kata-artifacts/scripts/kata-deploy.sh
          args:
            - install
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: SHIMS
              value: "fc"
            - name: DEFAULT_SHIM
              value: "fc"
            - name: CREATE_RUNTIMECLASSES
              value: "false"
            - name: CREATE_DEFAULT_RUNTIMECLASS
              value: "false"
            - name: DEBUG
              value: "false"
            - name: PULL_TYPE_MAPPING
              value: ""
            - name: ALLOWED_HYPERVISOR_ANNOTATIONS
              value: ""
          securityContext:
            privileged: true
          volumeMounts:
            - name: host-opt-kata
              mountPath: /opt/kata
            - name: host-etc-containerd
              mountPath: /etc/containerd
            - name: host-etc-crio
              mountPath: /etc/crio
            - name: host-etc-systemd
              mountPath: /etc/systemd/system
            - name: systemd-private
              mountPath: /run/systemd/private
            - name: host-usr-bin
              mountPath: /host-usr/bin
              readOnly: true
            - name: host-usr-sbin
              mountPath: /host-usr/sbin
              readOnly: true
            - name: host-usr-local-bin
              mountPath: /host-usr-local/bin
              readOnly: true
            - name: host-usr-local-sbin
              mountPath: /host-usr-local/sbin
              readOnly: true
            - name: host-bin
              mountPath: /host-bin
              readOnly: true
            - name: host-sbin
              mountPath: /host-sbin
              readOnly: true
            - name: boot
              mountPath: /boot
              readOnly: true
      volumes:
        - name: host-opt-kata
          hostPath:
            path: /opt/kata
            type: DirectoryOrCreate
        - name: host-etc-containerd
          hostPath:
            path: /etc/containerd
            type: DirectoryOrCreate
        - name: host-etc-crio
          hostPath:
            path: /etc/crio
            type: DirectoryOrCreate
        - name: host-etc-systemd
          hostPath:
            path: /etc/systemd/system
            type: DirectoryOrCreate
        - name: systemd-private
          hostPath:
            path: /run/systemd/private
            type: Socket
        - name: host-usr-bin
          hostPath:
            path: /usr/bin
        - name: host-usr-sbin
          hostPath:
            path: /usr/sbin
        - name: host-usr-local-bin
          hostPath:
            path: /usr/local/bin
        - name: host-usr-local-sbin
          hostPath:
            path: /usr/local/sbin
        - name: host-bin
          hostPath:
            path: /bin
        - name: host-sbin
          hostPath:
            path: /sbin
        - name: boot
          hostPath:
            path: /boot
