apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osc-kata-install
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: osc-kata-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: osc-kata-install
subjects:
  - kind: ServiceAccount
    name: osc-kata-install
    namespace: {{ .Release.Namespace }}
