hyperfleet:
  applicationName: hyperfleet-operator

  namespace: argocd

  targetNamespace: hyperfleet

  project: default

  source:
    repoURL: https://github.com/openshift-online/rosa-hyperfleet-api.git
    targetRevision: 3064a73d1d2641c6bf948dbaa2bfe1c5f480bf64
    path: hyperfleet-operator/charts

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  helmValues:
    image:
      repository: quay.io/cdoan0/rosa-hyperfleet-operator
      tag: "latest"
      pullPolicy: Always

    replicaCount: 2

    serviceAccount:
      create: true
      name: hyperfleet-operator
      annotations: {}

    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

