redis:
  image:
    repository: registry.redhat.io/rhel9/redis-7
    tag: "1-1782912632"
    pullPolicy: IfNotPresent

  port: 6379

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 64Mi

  metrics:
    enabled: true

  config:
    maxmemory: 48mb
    maxmemory-policy: volatile-ttl
    save: ""
    appendonly: "no"
